import type { NextPage } from "next";
import Wallet from "../components/Wallet";
import { useListen } from "../hooks/useListen";
import { useMetamask } from "../hooks/useMetamask";
import Head from 'next/head'
import Image from 'next/image'
import {Inter} from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from "../components/Navbar";
import React, {useCallback, useEffect, useState} from "react";
import CountdownTimer from "../components/CountdownTimer";
import Marquee from "react-fast-marquee";
import Deposit from "../components/Deposit";
import FarmBooster from "../components/FarmBooster";

const Home: NextPage = () => {
  const { dispatch } = useMetamask();
  const listen = useListen();

  useEffect(() => {
    if (typeof window !== undefined) {
      // start by checking if window.ethereum is present, indicating a wallet extension
      const ethereumProviderInjected = typeof window.ethereum !== "undefined";
      // this could be other wallets so we can verify if we are dealing with metamask
      // using the boolean constructor to be explecit and not let this be used as a falsy value (optional)
      const isMetamaskInstalled =
        ethereumProviderInjected && Boolean(window.ethereum.isMetaMask);

      const local = window.localStorage.getItem("metamaskState");

      // user was previously connected, start listening to MM
      if (local) {
        listen();
      }

      // local could be null if not present in LocalStorage
      const { wallet, balance } = local
        ? JSON.parse(local)
        : // backup if local storage is empty
          { wallet: null, balance: null };

      dispatch({ type: "pageLoaded", isMetamaskInstalled, wallet, balance });
    }
  }, []);

  const [navbarHidden, setNavbarHidden] = useState(false)
  const [currentScroll, setCurrentScroll] = useState(0)
  const [differenceScroll, setDifferenceScroll] = useState(200);

  const onScroll = useCallback((event:any) => {
    const {pageYOffset, scrollY} = window;
    setCurrentScroll(pageYOffset)
  }, []);

  useEffect(() => {

    window.addEventListener("scroll", onScroll, {passive: true});

    return () => {
      window.removeEventListener("scroll", onScroll);
    }
  }, []);
  useEffect(() => {
    if (currentScroll >= differenceScroll) {
      setNavbarHidden(true)
      setDifferenceScroll(currentScroll)
    } else {
      setNavbarHidden(false)

    }
  })


  const boosters=[
    'X2 ATOM BOOSTER',
    'X3 ATOM BOOSTER',
    'X4 ATOM BOOSTER',
    'X5 ATOM BOOSTER',
  ]

  return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app"/>
          <meta name="viewport" content="width=device-width, initial-scale=1"/>
          <link rel="icon" href="/favicon.ico"/>
        </Head>
        <main className={'min-h-screen overflow-x-hidden font-pluto bg-cover bg-[url("/images/bg_footage.png")]'}>
          <Navbar isHidden={navbarHidden}></Navbar>
          <div className={'p-2 sm:p-14 pt-16 sm:pt-28'}>
            <div className={'grid mt-5 sm:mt-10 grid-cols-1 gap-8 w-full sm:grid-cols-12'}>
              <div className={'sm:col-span-8'}>
                <p className={'text-white text-4xl text-center sm:text-left sm:text-8xl font-black uppercase'}>
                  Web3<span className={'text-blue'}> FARM</span>
                </p>
                <div className={'w-full border-4 rounded-xl border-violet bg-blue p-3'}>
                  <p className={'text-violet sm:text-2xl'}>Our WEB3 project is a decentralized cryptocurrency
                    exchange that utilizes blockchain
                    technology to provide users with a secure and transparent platform for trading
                    cryptocurrencies. Unlike traditional exchanges that are centralized and susceptible
                    to hacking or manipulation, our exchange is built on a decentralized network, which
                    means that it is powered by a community of users and not controlled by any single
                    entity.</p>
                </div>
              </div>
              <div className={'sm:col-span-4 flex justify-center sm:justify-end'}>
                <div className={'w-4/5 aspect-square relative'}>
                  <Image className={'animate-spin-atom'} src={'/images/atom5.svg'} alt={'atom5'}
                         layout={'fill'}></Image>
                </div>
              </div>
              <div className={'sm:col-span-3 flex flex-col items-center justify-between'}>
                <div
                    className={'w-full my-1 text-violet text-3xl font-bold h-14 bg-white rounded-full flex items-center justify-center border-blue border-4'}>
                  KYC
                </div>
                <div
                    className={'w-full my-1 text-violet text-3xl font-bold h-14 bg-white rounded-full flex items-center justify-center border-blue border-4'}>
                  AUDIT
                </div>
                <div
                    className={'w-full my-1 text-violet text-3xl font-bold h-14 bg-white rounded-full flex items-center justify-center border-blue border-4'}>
                  SAFU
                </div>
              </div>
              <div
                  className={'sm:col-span-9 p-2 flex flex-col sm:flex-row items-center justify-between h-full border-blue rounded-xl bg-violet border-4'}>
                <div className={'h-full aspect-square relative'}>
                  <Image src={'/images/main_info.svg'} alt={'main info'} layout={'fill'}></Image>
                </div>
                <div className={'flex flex-col sm:w-1/4 items-center'}>
                  <p className={'uppercase text-white text-2xl text-center font-bold my-2'}>Presale</p>
                  <p className={'uppercase text-blue text-2xl text-center font-bold my-2'}>15 april
                    2023 <br/> 14 UTC</p>
                </div>
                <div className={'flex flex-col sm:w-1/4 items-center'}>
                  <p className={'uppercase text-white text-2xl text-center font-bold my-2'}>SMART
                    CNTRCT</p>
                  <p className={'uppercase text-blue text-2xl text-center font-bold my-2'}>0x345465<br/>7457777865
                  </p>
                </div>
                <div className={'flex flex-col sm:w-1/4 items-center'}>
                  <p className={'uppercase text-white text-2xl text-center font-bold my-2'}>TIME TO
                    START</p>
                  <p className={'uppercase text-blue text-2xl text-center font-bold my-2'}><CountdownTimer
                      time={50056050} timeLimits={'minutes'} prefix={'MINUTES'}/></p>
                </div>
              </div>
            </div>
          </div>
          <div className={'w-full mt-4 h-20 bg-blue  flex items-center relative overflow-x-hidden'}>
            <Marquee gradient={false} speed={100}
                     className={'text-7xl overflow-x-hidden font-black text-violet'}>
              {'//'} <p className={'bannerText'}>FARM</p> {'//'} <p className={'bannerText'}>FARM</p> {'//'} <p
                className={'bannerText'}>FARM</p> {'//'} <p className={'bannerText'}>FARM</p> {'//'} <p
                className={'bannerText'}>FARM</p> {'//'} <p className={'bannerText'}>FARM</p>
            </Marquee>
          </div>
          <div className={'sm:px-14 px-2 my-24 '}>
            <div className={'grid gap-8 w-full grid-cols-1 sm:grid-cols-3'}>
              <Deposit boosters={boosters} firstCoinName={'BNB'} firstCoinIcon={'/images/coins/bnb.svg'}
                       secondCoinName={'PINKSALE'} secondCoinIcon={'/images/coins/pinksale.svg'}
                       rewardPerBlock={12.4345} timeTillEnd={555555}></Deposit>
              <Deposit boosters={boosters} firstCoinName={'BNB'} firstCoinIcon={'/images/coins/bnb.svg'}
                       secondCoinName={'PINKSALE'} secondCoinIcon={'/images/coins/pinksale.svg'}
                       rewardPerBlock={12.4345} timeTillEnd={555555}></Deposit>
              <Deposit boosters={boosters} firstCoinName={'BNB'} firstCoinIcon={'/images/coins/bnb.svg'}
                       secondCoinName={'PINKSALE'} secondCoinIcon={'/images/coins/pinksale.svg'}
                       rewardPerBlock={12.4345} timeTillEnd={555555}></Deposit>
              <Deposit boosters={boosters} firstCoinName={'BNB'} firstCoinIcon={'/images/coins/bnb.svg'}
                       secondCoinName={'PINKSALE'} secondCoinIcon={'/images/coins/pinksale.svg'}
                       rewardPerBlock={12.4345} timeTillEnd={555555}></Deposit>
              <Deposit boosters={boosters} firstCoinName={'BNB'} firstCoinIcon={'/images/coins/bnb.svg'}
                       secondCoinName={'PINKSALE'} secondCoinIcon={'/images/coins/pinksale.svg'}
                       rewardPerBlock={12.4345} timeTillEnd={555555}></Deposit>
              <Deposit boosters={boosters} firstCoinName={'BNB'} firstCoinIcon={'/images/coins/bnb.svg'}
                       secondCoinName={'PINKSALE'} secondCoinIcon={'/images/coins/pinksale.svg'}
                       rewardPerBlock={12.4345} timeTillEnd={555555}></Deposit>
              <Deposit boosters={boosters} firstCoinName={'BNB'} firstCoinIcon={'/images/coins/bnb.svg'}
                       secondCoinName={'PINKSALE'} secondCoinIcon={'/images/coins/pinksale.svg'}
                       rewardPerBlock={12.4345} timeTillEnd={555555}></Deposit>
              <Deposit boosters={boosters} firstCoinName={'BNB'} firstCoinIcon={'/images/coins/bnb.svg'}
                       secondCoinName={'PINKSALE'} secondCoinIcon={'/images/coins/pinksale.svg'}
                       rewardPerBlock={12.4345} timeTillEnd={555555}></Deposit>
              <Deposit boosters={boosters} firstCoinName={'BNB'} firstCoinIcon={'/images/coins/bnb.svg'}
                       secondCoinName={'PINKSALE'} secondCoinIcon={'/images/coins/pinksale.svg'}
                       rewardPerBlock={12.4345} timeTillEnd={555555}></Deposit>
            </div>
          </div>
          <div className={'w-full h-20 border-4 border-blue bg-violet  flex items-center relative overflow-x-hidden'}>
            <Marquee gradient={false} speed={100} className={'text-7xl overflow-x-hidden font-black text-blue'}>{'//'}
              NFT BOOSTERS {'//'} NFT BOOSTERS {'//'} NFT BOOSTERS </Marquee>
          </div>
          <div className={'my-24 px-2 sm:px-14 grid grid-cols-1 sm:grid-cols-4 gap-8'}>
            <FarmBooster boostIncrease={2} boostPercent={10} boostImage={'/images/atoms/x2.svg'} supply={200} price={0.25}></FarmBooster>
            <FarmBooster boostIncrease={3} boostPercent={30} boostImage={'/images/atoms/x3.svg'} supply={100} price={0.50}></FarmBooster>
            <FarmBooster boostIncrease={4} boostPercent={40} boostImage={'/images/atoms/x4.svg'} supply={50} price={1.50}></FarmBooster>
            <FarmBooster boostIncrease={5} boostPercent={50} boostImage={'/images/atoms/x5.svg'} supply={25} price={5.0}></FarmBooster>
          </div>
          <div className={'my-20 px-2 sm:px-14'}>
            <p className={'text-5xl sm:text-8xl font-black text-white uppercase'}>Roadmap</p>
            <div className={'grid sm:grid-cols-4 gap-5'}>
              <div className={'flex-col mt-6 flex justify-start'}>
                <div className={'flex items-center'}>
                  <div className={'w-4 mr-3 h-full bg-violet'}>

                  </div>
                  <p className={'text-5xl font-black uppercase text-blue leading-[70%]'}>Q1 2023 <br/><span className={'text-2xl lowercase'}>50% done</span> </p>
                </div>
                <ul className={'list-disc pl-5 text-white leading-9 text-xl'}>
                  <li>Planning & Team building </li>
                  <li>Website & Community </li>
                  <li>Farm pools development</li>
                  <li>Whitepaper Marketing </li>
                  <li>1st giveaway</li>
                  <li>1st community competition</li>
                  <li>Launch Farming pool BNB/BUSD/Pinksale</li>
                  <li>NFT booster sale</li>
                  <li>Fair launch $Web3Farm token</li>
                  <li>CG,CMC & CEX Listing</li>
                  <li>Launch Farming pool WEB3 token</li>
                  <li>CEX listing</li>

                </ul>
              </div>
              <div className={'flex-col mt-6 flex justify-start'}>
                <div className={'flex items-center'}>
                  <div className={'w-4 mr-3 h-full bg-violet'}>

                  </div>
                  <p className={'text-5xl font-black uppercase text-white leading-[70%]'}>Q1 2023 <br/><span className={'text-2xl lowercase'}>Pending</span> </p>
                </div>
                <ul className={'list-disc pl-5 text-white leading-9 text-xl'}>
                  <li>DeFi App launch</li>
                  <li>More Partnership</li>
                  <li>Marketing</li>
                  <li>Launch Energy token</li>

                </ul>
              </div>
              <div className={'flex-col mt-6 flex justify-start'}>
                <div className={'flex items-center'}>
                  <div className={'w-4 mr-3 h-full bg-violet'}>

                  </div>
                  <p className={'text-5xl font-black uppercase text-white leading-[70%]'}>Q4 2023<br/><span className={'text-2xl lowercase'}>Pending</span> </p>
                </div>
                <ul className={'list-disc pl-5 text-white leading-9 text-xl'}>
                  <li>Staking NFT</li>
                  <li>Staking Gov token</li>
                  <li>Staking Energy token</li>
                </ul>
              </div>
              <div className={'flex-col mt-6 flex justify-start'}>
                <div className={'flex items-center'}>
                  <div className={'w-4 mr-3 h-full bg-violet'}>

                  </div>
                  <p className={'text-5xl font-black uppercase text-white leading-[70%]'}>Q1 2024<br/><span className={'text-2xl lowercase'}>Pending</span> </p>
                </div>
                <ul className={'list-disc pl-5 text-white leading-9 text-xl'}>
                  <li>Staking NFT</li>
                  <li>Staking Gov token</li>
                  <li>Staking Energy token</li>
                </ul>
              </div>

            </div>
          </div>
          <div className={'my-20 px-2 sm:px-14'}>
            <p className={'text-2xl sm:text-8xl font-black text-white uppercase'}>Partners</p>
            <div className={'grid mt-4 sm:grid-cols-4'}>
              <div className={'w-full h-40 flex items-center justify-center bg-violet'}>
                <img src={'/images/partners/binance_blue.svg'} className={'w-3/4 h-32'} />
              </div>
              <div className={'w-full h-40 flex items-center justify-center bg-blue'}>
                <img src={'/images/partners/binance.svg'} className={'w-3/4 h-32'} />
              </div>
              <div className={'w-full h-40 flex items-center justify-center bg-violet'}>
                <img src={'/images/partners/binance_blue.svg'} className={'w-3/4 h-32'} />
              </div>
              <div className={'w-full h-40 flex items-center justify-center bg-blue'}>
                <img src={'/images/partners/binance.svg'} className={'w-3/4 h-32'} />
              </div>
              <div className={'w-full h-40 flex items-center justify-center bg-blue'}>
                <img src={'/images/partners/binance.svg'} className={'w-3/4 h-32'} />
              </div>
              <div className={'w-full h-40 flex items-center justify-center bg-violet'}>
                <img src={'/images/partners/binance_blue.svg'} className={'w-3/4 h-32'} />
              </div>
              <div className={'w-full h-40 flex items-center justify-center bg-blue'}>
                <img src={'/images/partners/binance.svg'} className={'w-3/4 h-32'} />
              </div>
              <div className={'w-full h-40 flex items-center justify-center bg-violet'}>
                <img src={'/images/partners/binance_blue.svg'} className={'w-3/4 h-32'} />
              </div>
            </div>
          </div>
          <div className={'bg-blue w-full p-3 sm:p-14'}>
            <p className={'uppercase font-black text-violet text-2xl sm:text-4xl'}>HAVE QUESTIONS? WRITE US!</p>
            <div className={'grid mt-5 gap-5 sm:grid-cols-4'}>
              <input onChange={(event)=>{}} className={'h-12 w-full rounded-full text-violet font-bold border-2 border-violet placeholder:text-violet placeholder:opacity-50 p-2'} placeholder={`Name`}/>
              <input onChange={(event)=>{}} className={'h-12 w-full rounded-full text-violet font-bold border-2 border-violet placeholder:text-violet placeholder:opacity-50 p-2'} placeholder={`Question`}/>
              <input onChange={(event)=>{}} className={'h-12 w-full rounded-full text-violet font-bold border-2 border-violet placeholder:text-violet placeholder:opacity-50 p-2'} placeholder={`Email / Telegram nickname`}/>
              <button className={'bg-violet h-12 rounded-full text-white font-black text-3xl'}>SEND</button>
            </div>
            <div className={'w-full mt-14 animate-navbarOpen transition-all duration-300 mt-3 grid sm:grid-cols-7 items-center'}>
              <p className={'text-2xl uppercase font-semibold text-violet text-center  cursor-pointer '}>Presale</p>
              <p className={'text-2xl uppercase font-semibold text-violet text-center  cursor-pointer '}>KYC</p>
              <p className={'text-2xl uppercase font-semibold text-violet text-center  cursor-pointer '}>AUDIT</p>
              <p className={'text-2xl uppercase font-semibold text-violet text-center  cursor-pointer '}>SAFU</p>
              <p className={'text-2xl uppercase font-semibold text-violet text-center  cursor-pointer '}>Docs</p>
              <p className={'text-2xl uppercase font-semibold text-violet text-center  cursor-pointer '}>Telegram</p>
              <p className={'text-2xl uppercase font-semibold text-violet text-center  cursor-pointer '}>Twitter</p>
            </div>
          </div>

        </main>
      </>
  )
};

export default Home;
